
export const sliderData = [
    {
        img: "/1.png",
        location: "HIỀN",
        description: "Em như dòng nước trong veo Xoá hết ưu phiền băng qua ngọn núi vòng vèo",
        title: "Bình yên",
        song: "/music/song-1.mp3",
        progressColor: "#a2d2ff",
        waveColor: "#d4a373",
    },
    {
        img: "/2.png",
        location: "HIỀN",
        description: "Có ánh mắt câu thơ dịu dàng",
        title: "Không yêu em thì yêu ai",
        song: "/music/song-2.mp3",
        progressColor: "#bde0fe",
        waveColor: "#faedcd",
    },
    {
        img: "/3.png",
        title: "Anh nhớ ra",
        description: "Anh nhớ ra rằng mình biết yêu em là gì",
        location: "HIỀN",
        song: "/music/song-3.mp3",
        progressColor: "#ffafcc",
        waveColor: "#fefae0",
    },
    {
        img: "/4.png",
        title: "Bước qua mùa cô đơn",
        description: "Chào hàng cây, làm sao cố níu tay nhau lại để thấy nồng nàn, đang về trên đôi mắt em",
        location: "HIỀN",
        song: "/music/song-4.mp3",
        progressColor: "#ffc8dd",
        waveColor: "#e9edc9",
    },
    {
        img: "/7.png",
        title: "Lạ lùng",
        description: "Lạ lùng Em với gió hát lên câu ca làm Anh thao thức",
        location: "HIỀN",
        song: "/music/song-5.mp3",
        progressColor: "#cdb4db",
        waveColor: "#ccd5ae",
    },
];
